### ISSUE TITLE
UnidecodeError when installing kefir

### ISSUE THREAD

**Issue by hakanutku** [yogurt-cultures/kefir#7]
When I try to install kefir I get this error: 

Collecting kefir
  Using cached https://files.pythonhosted.org/packages/ac/bc/2b33a0657cda729faedefb896b4e1315251dc38387763cf3973ca0b758c7/kefir-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Username\AppData\Local\Temp\pip-install-xf5i6hha\kefir\setup.py", line 37, in <module>
        readme = f.read()
      File "c:\users\username\appdata\local\programs\python\python36\lib\encodings\cp1254.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2554: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-install-xf5i6hha\kefir\

**Comment by fatiherikli** [comment]
Can you give us a more detailed reproduction flow?

 - Did you use "pip"?
 - What's your python version?

**Comment by hakanutku** [comment]
- Yes, I have used "pip install kefir" command.
- My python version is 3.6.3
- My pip version is 18.0

**Comment by fatiherikli** [comment]
I've never tried installing kefir on windows. Looks like it's because of turkish characters in the codebase.

**Comment by fatiherikli** [comment]
#7 is merged. Probably it'll be resolved in next release.
